@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Appointments

GET {{DientesLimpios.API_HostAddress}}/019e25d3-7405-7cfe-9689-b62396082b20
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9nGTtOF_sdUcSIxS256JQdgGYLMtG_P-jERHTegOl0jdUI00yXSYm4QMeNhZDl-0gS__8s2u4igGrH6--1thc70LV053GAssYULKJdonQrwuiFiHAVQKYqFT2-4ua0FZZwXBqEtY3a7VvVCPIs-yjXt51pc46CStTYqNqJldE8STFGSBc4-_Px5RbD4jmGzmVqVaGyrR_i7KYF8WOMGsMZRhuV12Tq7oGG3K3ZSyVaItueedyIwkENqD4vEnhRQSAXspCqqvfJwjKkajLqTUEZcXIgT_WdAv_U_XFl8eHV2FXIczjdrRXWk2v62MA1gA3J2cN4fameQJikoXuqwQ4sx3P6tbjrWZz_LxexYq2g4fc27mhAGJCFVcPKcoX9gtUpPSoIQWsMFtdQoJJ0vfKhL2YSQmj7odvU-TVt_YeE-8RVVZcuwbGmcEObd6eks7quaTUcZyez7EmlRjuDOzmavTTqsMWV6xVff8mmrxopW09hHBvV6yRoawoMmsW4T5gZpaA1vI48y9RmTsqT6BdmUxN3yDKpUqH7iAtisrXe8Uv1NxuXp6gYqRNXbf-I8lDxiGX2x-apHqgrncc2nDhdZ3_0ZP-gOuWGHGjq9zemqw4onZGJdCjb-v1zC6L-Ko3jY8__HY96AqNbyN6TE7DApw8-9drX1vjxBtTl70L-QhZHfL-I1GSisL0dNGRvJLfnkKD3NhwJHB8j9sMZSHS0h

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9nGTtOF_sdUcSIxS256JQdgGYLMtG_P-jERHTegOl0jdUI00yXSYm4QMeNhZDl-0gS__8s2u4igGrH6--1thc70LV053GAssYULKJdonQrwuiFiHAVQKYqFT2-4ua0FZZwXBqEtY3a7VvVCPIs-yjXt51pc46CStTYqNqJldE8STFGSBc4-_Px5RbD4jmGzmVqVaGyrR_i7KYF8WOMGsMZRhuV12Tq7oGG3K3ZSyVaItueedyIwkENqD4vEnhRQSAXspCqqvfJwjKkajLqTUEZcXIgT_WdAv_U_XFl8eHV2FXIczjdrRXWk2v62MA1gA3J2cN4fameQJikoXuqwQ4sx3P6tbjrWZz_LxexYq2g4fc27mhAGJCFVcPKcoX9gtUpPSoIQWsMFtdQoJJ0vfKhL2YSQmj7odvU-TVt_YeE-8RVVZcuwbGmcEObd6eks7quaTUcZyez7EmlRjuDOzmavTTqsMWV6xVff8mmrxopW09hHBvV6yRoawoMmsW4T5gZpaA1vI48y9RmTsqT6BdmUxN3yDKpUqH7iAtisrXe8Uv1NxuXp6gYqRNXbf-I8lDxiGX2x-apHqgrncc2nDhdZ3_0ZP-gOuWGHGjq9zemqw4onZGJdCjb-v1zC6L-Ko3jY8__HY96AqNbyN6TE7DApw8-9drX1vjxBtTl70L-QhZHfL-I1GSisL0dNGRvJLfnkKD3NhwJHB8j9sMZSHS0h

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9l8Zc0DTiWwA5wJ1ujdFvUFgz_4XULC78TlNcTCvDY5sUZzSHshDlCo4Mx7xESnOr9JjvLkEH7HHn1e6XPqwiIImDshtAhZ6JWGoTtX28DNbXafjv5uqUVsTQXWX6ApTQItV7oWEQ260cF4O6XT5G8Bb1WFKzzdkPDsE3I9I3EE-fJWyQdo3SsNVPDfzoc0x7C7dKuXQAxi8eVz4yH-lChNHbeJfVHPxyIblJ1MnLYjeLqDaY83eRJKeAwRtfwCbTfSgEQgFOSglk4JxP8frgMZnqCwcG6HgfS0pUEG1oGvBtG-u3AYb_VFIcPMQDGht0HRW9wouY1QUWVg0JgEV35a5E9fL-e3tX7dGedX53v9MKgc346eDD-GOVK0kkdTL7MOnx93wS1fZ_r9-W_O7ab0O3KuZ-OVCSAabeOwZTohW5Tzer_CSPy-FI6DdNsrmSafrjTDWTQJansr87deMwDFw9zO9ALUgJo7YEcyGdEQwBVDBzL6ngYYtuMdOrJAgPI7gnD0_igedrUXdjh_9_UqPqf4Uro7T4gnpBujRpq1_i7FRbUIpKoEzlcxJ2gYwYOr9ZDvkiR4XP0TMXG8JDInH8qVKqrErCzueCg8qtw35Zgb6bzw0mhnR8E-0R_OIClDcdE7_0VkeKfhTyVLtCd4BBxGmF2nf6v0yQuwaXksM3ZBPvGuxUJdE08DjcTM7Nodrd0HdeMiYtTpAtUtO-7i

{
  "PatientId": "019e2602-9742-7ef0-b968-e5d40eff6682",
  "DentistId": "019e25c6-724c-7087-9158-f95d06aa973f",
  "OfficeId": "019e25bd-3f14-755c-a08c-1cba409319dd",
  "StartDate": "2026-05-15T14:30:00",
  "EndDate": "2026-05-16T14:45:00"
}

###


POST {{DientesLimpios.API_HostAddress}}/complete/019e25d3-7405-7cfe-9689-b62396082b20
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9nGTtOF_sdUcSIxS256JQdgGYLMtG_P-jERHTegOl0jdUI00yXSYm4QMeNhZDl-0gS__8s2u4igGrH6--1thc70LV053GAssYULKJdonQrwuiFiHAVQKYqFT2-4ua0FZZwXBqEtY3a7VvVCPIs-yjXt51pc46CStTYqNqJldE8STFGSBc4-_Px5RbD4jmGzmVqVaGyrR_i7KYF8WOMGsMZRhuV12Tq7oGG3K3ZSyVaItueedyIwkENqD4vEnhRQSAXspCqqvfJwjKkajLqTUEZcXIgT_WdAv_U_XFl8eHV2FXIczjdrRXWk2v62MA1gA3J2cN4fameQJikoXuqwQ4sx3P6tbjrWZz_LxexYq2g4fc27mhAGJCFVcPKcoX9gtUpPSoIQWsMFtdQoJJ0vfKhL2YSQmj7odvU-TVt_YeE-8RVVZcuwbGmcEObd6eks7quaTUcZyez7EmlRjuDOzmavTTqsMWV6xVff8mmrxopW09hHBvV6yRoawoMmsW4T5gZpaA1vI48y9RmTsqT6BdmUxN3yDKpUqH7iAtisrXe8Uv1NxuXp6gYqRNXbf-I8lDxiGX2x-apHqgrncc2nDhdZ3_0ZP-gOuWGHGjq9zemqw4onZGJdCjb-v1zC6L-Ko3jY8__HY96AqNbyN6TE7DApw8-9drX1vjxBtTl70L-QhZHfL-I1GSisL0dNGRvJLfnkKD3NhwJHB8j9sMZSHS0h

###


POST {{DientesLimpios.API_HostAddress}}/cancel/019E2603-F989-79BC-92C8-E9A4B8C1A456
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9nfRdsw3gZPkCv9qUcJquyyTmUufo37oEdGpwvW1lS7RB87jyLuIj-Esx-cbPQKxOscK32qRCbOoaNqRXUiU4aqNXB_83Hc40RfBfAKYr0q8jBlPqH6JNrKkGaxRyMdvXJKD8o5h47750ThZ1OWUaJpDZMvjrDhFvRGgo_fdtS8EzRpc0oKF0FYqrHfyiaFMIWga-ZLjaXOCgq-QzHRtvPLKbDzuovJfbtOQbPk4YjwREALjKoESrK2b2Y6vzY_ETPslohaP70-PyEk3PsEYOtGCvAyuxKbL8xnDCGbxmIt6V2XpXWnPi4ppFX-h4k5FSUAJgfN-7Yl_Iy2P20pmzusRPE0OpikA9hwND3rKgWVXQgpuuS98l55tuOC-HlDyAMcfmM9E2r1U9p8_x7kbDzMBatnBuSau6dU2e0zAwEyNDX6zhYDqz5N-jMV3pz67yLA0mLK-SBuE39wddzQrugyctfDY4nXUR7RryC5pNUyIWm7EPHPO2qWX1T-6jAZrpqH7wad16UXAU2Hfegh1oIlzPYN8Nyh6ypCi5YN3PtRpqRvKtR7WgzL2k-6tO-mrQCIfOrigkBH70CpdDc4rq7MWxeonT7mqielhfd4SkPvJS0lvrOBkO0HfB6b7s57WpVldjWUWOUFr0XDD-03dRa1tyVJmpU92aDyjkBg6KsZRCB4mQRdznQuEcupTlEUcm2qSespuMNlt3l5Yi6CNIga

###


POST {{DientesLimpios.API_HostAddress}}/reminder
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9kJ7xUoHDCq3E_HskrINFiKCC9FQoqBP7BnymBCjSRzAoRNCtagX-0uwlXNuIOczl-wXSjiKP_tWCGuCcXpQ0LeR9-QgvJgFFdfDA2TAvZ2SankG02lI3VelOKerw3NKRrRz7h_tIJEarW0Ta2TBlqFoOGKKvEvQitxlHF_npm-f3qjWV8d_MZRkhA0sFqk2RcznchfDiUuKc7iIUkKrbHB8MyD7mPIIwyE9JLOzllg0TdtC5rum_bPaseJ_Vd9pz77dXtVkWX5usEw4dHNSCG-r6CRBFQqKGSaEcXVnANyd8V1cmWuwD5McR8DbXk92hd5engHyDux_ZHjtedQ7-GXjGjfPq22Ge-rPZYnGsViQuB3dUadDLImpiD73-fjE53PZ_LOQIIOMyMCYZZHhMPSSHeuaK4YaoWA8BNYT5-IfKKww5r3dpPcaMPTp0HZI_TiS1c6g8bC87LnbNPRxhashsTBMkln-dedu-CUcAuQElekrv3atyWyiIWEtM2ZyuZGVMozgA12SyJBKH9HsGZ2Or72vLq4A7fuQKS31ZGvbFeIh5WL_2e_KHS900ghkfB7ok_8Nn-oa86RRj4w9aHnBJJVF8JDdcXdVvcBEkzcZkHhFVITpH2DGqRsuy8ogd0f28WFYkUpFtGVbKyaKbdfVfYE7v0ii388vBgBDQLQLS0K_eI4ouC_SSpEwcElFSnRnrVBdlLQnjE7KiactEpr
