@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/consultorios

GET {{DientesLimpios.API_HostAddress}}/019b7ee6-29e8-70af-a4f5-a21c78d0789a
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C
###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-r-dXI3oKc9PBSzal4Bai5sOiyFcggjQJ1Z2DmI5jUOMeJ89w5LP58AkXNHMRsm2-AfP_oEoPl7Soh7W6gQNnPeLdMxNIUV1uOubj_MgYV-Rv9ojkVl7BrDHE_M7fm7R9yg-rp4tBQfS3Pjs8UYOidTHeK9wOaLisgs6VspHp9Hm2VrgmoUfRwaeCYZ2vOBWLDTbf_qW5Yjo_dK4EirRPV8wHI8M0Pznv09JOYqC3_r8uuK0fUC6PFg1NUSv_-xKNe3uTWkIuHHr1l7ddmooNrz8ygdjBT7EUeZi2FLcz67H-ZX_c1rGGmO41McLywoAMajZxLh1qqT-varRNULHhn5AquQVO8iaZcw8Tpu3a7w6-IVReSxBW1IHgZzA2bYurQkeE3xVpa41IgBt_I109Z71BOebYEpVyfNdSNd0HimsgfV_WkD3Rdb936UhmDKo2VrGGHQ9FofTh3bzyMU3uicGe2Mc6v3k1n1sUX4DWEhTsg5HnkkGO1m0EUP0TyvzmF7Jh-zlivqHpTvyi82XZviJqUTJWXlCvb-F_li6XZeWtzBj0RhfNtKojWP1ahahkCb8ypoo_5gSnTY37-UhjXdrQfAWNYEnprElY1_9SYbVuva3C7vd_RgFi0D8wJAAOPFgRimXdu-kLNKXPCO30Dc5NuCuNL6yAl9LZIllnl6E6B6dsTMSLR5AEDZAOEddxOyV8EWzylLGTHJ6bNtUGs

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-UZdjdzRCyK-T_-GlNoht1vjrov7H-dnwg7ua8hZxROvTKtvLQM64VtxcljHR4nMvNEfXSyypNlB477zbtrLZj7j9tJi7f9i-TwIGp9T5BO8p3oYJH8ATENCDaIL0wCwe2XVJQYj6GJ9EWSiDD1shZSQTApC_Q5W2l5yDng1-cgUjNDbOQQ99nXcjvtIC2tn8g35Vzg-HlA4CMMb0zf7ZD4pHEPl3SbP8IApfb1ARDu5fTW8ZtW0S3BXmHhekNMikqpKOCgYlSldFwsT5-_QU90U7czsJSfH0UXRcf-umZx98zMx9yausClEtIjxnjV1lFsg8V0VmeVBQ_THb9J0YC3cNKlay8dFO97XlCIf3F09fodXlnBXtljr4HhnWB-oudcwmj1XUWcnZKe1u5xNIVjBoCe8twRFXGZFAYdfiJ20oOhvfMLZO8tXH2Sy1dF3kCr8NskAAmLxFTU8nHxnGtqzWVZFn_6uNIMooLfsNbWT8wSN4w3NOev_kIsA8g4zTurHpcMXXJ88VQM44b3iKAfoS_AFRTMAB-zw2hhSF8f1eUp29FWVobl6sU-qqEow8NVqbIqX_A9mDzS8dpCp9BSl157jmaOEVxAdVKntOXia5ObdlW81WAqYGD__jsnZaqhRLF0YbsMC7JEQr5AlGMWuTAzD-MUEFmaEiU9jmo7kg1X22sV_ITUp2xreeS8mj2AXLXvB42FcK7gBETYVNj

{
  "nombre": ""
}

###

PUT {{DientesLimpios.API_HostAddress}}/019b7e93-4c69-7166-a849-aea6452effb8
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C

{
  "nombre": "Consultorio C -Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019b5ebc-b162-74e0-9be9-da8a48e4d67a
Accept: application/json
