@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/consultorios

GET {{DientesLimpios.API_HostAddress}}/019b7ee6-29e8-70af-a4f5-a21c78d0789a
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C
###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e9qzUippWb1_ScWHYJkB8ixrYHZOrQhNUbU3bdmAgw-2KJmOnV5uPEClgNS22gytyC-TaBK-uhng_JF10nin-Qji8uXxsLKp0DMssflPZ9rBiXw4FHw8Wv_LVW2ODnbJl6-nQ1KDWivPpoMNFDVAxCRBcy50T1e5WqCuLl4ipPbUJsr1PhzEnzMkWZ4OVct0libUvWnpMe6mPsUxLmwgZdyTI2-waszBUVAD_EJRtjOnok7crzD7E3_7eAuiOCYxvCbh6Cq0gc7o0Kg6I5nUbXq0Qp2sysv576O2JhKE3mEqw76MfbLo1rEC97GrvwFiDbjEbH4_AaG3X6f89g6nJVwnMpx602mrUOLKTF-egQwxUiOzsk3c-R1uH0UgJNW75L_HSHJkguyQrBkE1IgoeYNwlx42RA8iwX6NDabRW-bUtX17B5JpKssvulEnvXXV5cy4UwFx054Zup321_6eAehkjd4MdKyLddYv_yg9KcT-ZYsQa6SLtGS39aoaNtnNJ-S2IBKC0_OumSMdDi0vAWcAa4KS3ok96LKaACLvSKHdf5h_MaAFA_9wsWVCWF3CoRyXkdtZGkDk7Gsp6XkRMKyJsJ35A7WyI8ooiMUfX0rUzBiThiM-GhSlWQJ9PgpZRlMAbAtZSKbMidrjphq5DaOlILbolcgR-wHbGlIanDuqBSAJEv-1IHcS9WPC1Ifl43lp7ihQGsP0RZJvlPObuj2

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C

{
  "nombre": "Consultorio C"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019b7e93-4c69-7166-a849-aea6452effb8
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C

{
  "nombre": "Consultorio C -Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019b5ebc-b162-74e0-9be9-da8a48e4d67a
Accept: application/json
