@DientesLimpios.API_HostAddress = https://localhost:7199/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/019b7ee6-29e8-70af-a4f5-a21c78d0789a
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C
###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e_dpydSJRd8RTKCBIKXcEUqqkQ8SwaWWfJuopfduY4UkdUUVkSRXMCpZN50-azH4yUZ-Ymgwx9n3sgGaE0o1DmvfCz40_zaonej9OlcVKVvkzk24_ULLZgPxAXSIpc3X-ZrHfW02CfW2fmppqGES1gXzVgQ17KG9KTctjoCYg5Rggam4sn3wWf-sMFm1jz3Fi2ZLj4ZsN19iromoOX77c_qS7W9dhCOc_5f4SkT77BlBnBavudHmfXVymCbmhA8XFORz5mOLMO5fC6n88OK43T_GdH8OOo2zTxWwcr_rY4zrn7qYUppSXOSKHiLWPDc-c3OtUX2bK4h_PfEnSWVzYxtuxVFIdoOUIU5T8Jok8FBBTMOJFcuJy3CJWhW8Df74OfacKx-581lCnmjtHBX9Gzzudqkw7nBUlqurZG0L9Ik9gIqe0OH9PJ4Lcs1kv7abVs180UQzWTBlyayhrIukhmXOAtZ0s0B4ejYBT3fGiAfOx1J03faTJApd7kC5IJjmqzPdGvd3O6qqsmGVywqdEO_9pa9KgZRlw2r7vKqt7P-wxYMNPuNwO7wGfj_PxYfH8qJNj_xJjv6RzIdqZAX3M1ZTWNrFQOX9h5B8e_XbHkRJnxyRnqDbs1L6muK_dR1muCB49sViWdkQyhFyyf1P93sVjiNfTC6UL-7DSCJuWHMeODi1Z3ZYrVcsXO_qPEkMxc

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C

{
  "nombre": "Consultorio C"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019b7e93-4c69-7166-a849-aea6452effb8
Content-Type: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e-JPkHXeiq2UQ9_vPowRWkBj1TeXnod2Ny_cgD_ASLRCF8d-jUUTbeQ2T_bfkWbswhnxdE3cZVGkOU6-BUc5Ojmp9NbsQHIG9C5ZY9xpQs1w0a7qJHqZ6cVpxHvW6q8YSX6fj3pi7-QJQcTfRXwzeMsqTmCqRfdf2e3NUzMwMLL_NR0g-E3Y2uOx3cWluwwQbG4EVtmKrVVoaqIcif7njdzItujD6v7WwWbT_ZqB3ZoiwRz5Vy2B24n_Z4mmuO7CKR_qQLJLO_o-JLvDy7IMn3eq7JIjhw7xQf_aZVs5SpLREt-oMwjRcR_ccttfMUu4GOft5F2v8sqr8ZmvCgoBFBE-swYDa9d7SHykZsUXfJCkSoiNH_8wk8NlUC75pxmSYI5UjluagebRTLBI0gHgWFPxOkCDGRBUZc8oSWbnJjxVwgHLd-HK65KSHuBfBvJiVrgn6tHaVvFtSFPnEQTVkUoX6dpq4b_RaG3ZeTMgTVpkYHt_uheRZJ--8kl_nQYAt7U8yFZffdAWrX1vtYe4kxsZaaujWNWGL93jeHDbId79dc3dRLW71eZTM_RmtO6zHmMel2OLAy9xDPxX_au78s-hrNR2pSRraLGpgIM8UokO5GD8nKc-8Y2uroynCoWqyL8fS1FU-ztpb89ZGU2Oh_kXYogJoRig9LivPjefm1UA3I8q95WOCTmMdPRu4_Mj0TrvzfQ86hTnEf8glY87e4C

{
  "nombre": "Consultorio C -Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019b5ebc-b162-74e0-9be9-da8a48e4d67a
Accept: application/json
