@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Dentists

GET {{DientesLimpios.API_HostAddress}}/019e25c6-724c-7087-9158-f95d06aa973f
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Dentist Daniel",
  "email" : "Daniel@ejemplo.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e682d-dcc4-70db-8af6-198c65039206
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Dentist Daniel Updated",
  "email" : "DanielUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25c6-724c-7087-9158-f95d06aa973f
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl
