@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Offices

GET {{DientesLimpios.API_HostAddress}}/019e25bd-3f14-755c-a08c-1cba409319dd
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc
###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Office B"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e682a-fd77-72df-a546-8f99d535beb6
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Office B Updated"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25ba-9326-7a41-8f18-bbf349021ead
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc
