@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/pacientes

GET {{DientesLimpios.API_HostAddress}}/019b6922-1e5a-7363-92ef-3a2ae6df42e4
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8AjPuzL6wyBPmF8c2rZ0-e9qzUippWb1_ScWHYJkB8ixrYHZOrQhNUbU3bdmAgw-2KJmOnV5uPEClgNS22gytyC-TaBK-uhng_JF10nin-Qji8uXxsLKp0DMssflPZ9rBiXw4FHw8Wv_LVW2ODnbJl6-nQ1KDWivPpoMNFDVAxCRBcy50T1e5WqCuLl4ipPbUJsr1PhzEnzMkWZ4OVct0libUvWnpMe6mPsUxLmwgZdyTI2-waszBUVAD_EJRtjOnok7crzD7E3_7eAuiOCYxvCbh6Cq0gc7o0Kg6I5nUbXq0Qp2sysv576O2JhKE3mEqw76MfbLo1rEC97GrvwFiDbjEbH4_AaG3X6f89g6nJVwnMpx602mrUOLKTF-egQwxUiOzsk3c-R1uH0UgJNW75L_HSHJkguyQrBkE1IgoeYNwlx42RA8iwX6NDabRW-bUtX17B5JpKssvulEnvXXV5cy4UwFx054Zup321_6eAehkjd4MdKyLddYv_yg9KcT-ZYsQa6SLtGS39aoaNtnNJ-S2IBKC0_OumSMdDi0vAWcAa4KS3ok96LKaACLvSKHdf5h_MaAFA_9wsWVCWF3CoRyXkdtZGkDk7Gsp6XkRMKyJsJ35A7WyI8ooiMUfX0rUzBiThiM-GhSlWQJ9PgpZRlMAbAtZSKbMidrjphq5DaOlILbolcgR-wHbGlIanDuqBSAJEv-1IHcS9WPC1Ifl43lp7ihQGsP0RZJvlPObuj2

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Antonio Garrido",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019b6a2f-0fbc-7347-9a3b-edc43cbe56f6
Content-Type: application/json

{
  "nombre": "Laura Marquez Cuevas",
  "email" : "LauraUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019b6922-1e5a-7363-92ef-3a2ae6df42e4
Accept: application/json
