@DientesLimpios.API_HostAddress = http://localhost:5298/api/pacientes

GET {{DientesLimpios.API_HostAddress}}/019b6922-1e5a-7363-92ef-3a2ae6df42e4
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Antonio Garrido",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019b6a2f-0fbc-7347-9a3b-edc43cbe56f6
Content-Type: application/json

{
  "nombre": "Laura Marquez Cuevas",
  "email" : "LauraUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019b6922-1e5a-7363-92ef-3a2ae6df42e4
Accept: application/json
