@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Patients

GET {{DientesLimpios.API_HostAddress}}/019e25c9-f49b-7beb-99f9-479efcf270e2
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9l8Zc0DTiWwA5wJ1ujdFvUFgz_4XULC78TlNcTCvDY5sUZzSHshDlCo4Mx7xESnOr9JjvLkEH7HHn1e6XPqwiIImDshtAhZ6JWGoTtX28DNbXafjv5uqUVsTQXWX6ApTQItV7oWEQ260cF4O6XT5G8Bb1WFKzzdkPDsE3I9I3EE-fJWyQdo3SsNVPDfzoc0x7C7dKuXQAxi8eVz4yH-lChNHbeJfVHPxyIblJ1MnLYjeLqDaY83eRJKeAwRtfwCbTfSgEQgFOSglk4JxP8frgMZnqCwcG6HgfS0pUEG1oGvBtG-u3AYb_VFIcPMQDGht0HRW9wouY1QUWVg0JgEV35a5E9fL-e3tX7dGedX53v9MKgc346eDD-GOVK0kkdTL7MOnx93wS1fZ_r9-W_O7ab0O3KuZ-OVCSAabeOwZTohW5Tzer_CSPy-FI6DdNsrmSafrjTDWTQJansr87deMwDFw9zO9ALUgJo7YEcyGdEQwBVDBzL6ngYYtuMdOrJAgPI7gnD0_igedrUXdjh_9_UqPqf4Uro7T4gnpBujRpq1_i7FRbUIpKoEzlcxJ2gYwYOr9ZDvkiR4XP0TMXG8JDInH8qVKqrErCzueCg8qtw35Zgb6bzw0mhnR8E-0R_OIClDcdE7_0VkeKfhTyVLtCd4BBxGmF2nf6v0yQuwaXksM3ZBPvGuxUJdE08DjcTM7Nodrd0HdeMiYtTpAtUtO-7i

{
  "name": "Patient Antonio Javier",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e25c9-f49b-7beb-99f9-479efcf270e2
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc

{
  "name": "Patient Laura Marquez Cuevas Updated",
  "email" : "LauraUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25c9-f49b-7beb-99f9-479efcf270e2
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9ld8yZGE2dOCR0lxGpiEEr9FmXfj9dHU9cjSPK6atNohirydre87fzWCCdMJZkkx7Q474okKYDtfAjckzCcWhfdzlPxKpBQZOgrfVNcbXkHUvRWvN7fo3srH9eFyZyvi1E3A6GLLS1KLhmT64K_Ns-ODMShc4bnS0xChjj2wAF1Xecf4Qyk1PNYHKCC2wZVS13Lz5gJNmc_wknHOY6VJSt_APlfTijRlogIzoPFFukcCFL7IrwB95Fkkk5kWpTvNFi6IdiGMvKs8eby8IE46cfl7J2Qe8AHz61BBMZPlnmpW6qFOXMAu1fvxS0cpw26f2zUlo_8XgmeiKUZdw4NfCvdfwftUaoq0BW2uVsJIY-jJQzE5Qa5f7uqVeqxNHCDB3ZST0Gs3igQa0gwILApGwOAkjI02-sRCAswDYrgiAeV6ghYUXtU5DR5xRSoQKg_2ruwGKb8gKMfUildIcd51sZisoO0UuhQYBLk0jWaHEBejLO-_BC3upzD4MvYwCwl0hcL7_hMZlrgKd6XhF4h9QfUdXVSyJO1BimYQ1xq3ckx_rokD9P2JU4dZFyo5IcrSnQ9Jg35lqUt7hNI8g4v9VslAzkWCwMCJxWmzJ98c3TdtxnRFcICv1Id1UhqhD-9NzBUlVkYyeSe8BRHmjbParpNOWEU9_oiBZx5--g1Fu5cUUOcp6j0M91c_uoLGfIL0BIkC-yY5fCJkjJEdookHoNc
