@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Patients

GET {{DientesLimpios.API_HostAddress}}/019e2602-9742-7ef0-b968-e5d40eff6682
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Patient Laura",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e6831-c64b-7cda-b906-43f05373a901
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Patient Laura Updated",
  "email" : "antoniojaviergr@gmail.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25cc-d9f5-7fdf-bbc2-f872756e6e74
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl
