@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Patients

GET {{DientesLimpios.API_HostAddress}}/019e2602-9742-7ef0-b968-e5d40eff6682
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8FkyPjhqepVDufk2KayVWTc5mVJ4OH1F1NoD2JoQgpOSVFG201dDNnGDGesauQS0t1wuwvKee2ni5KFrrcI43jDWKuC5OZEjYUd4-DGujeL38I98_BhrFtLwmpayuWMjYSt_MfiMt9wclMbeKz9WwioidWIQMygef60quf9d6vRgad6ABIc86K3_TdBtY5xM_wWqSJpmbH5G1OWt8ZJCUOF44b6yCUClJVEUMRKk3CMtYZvk5608V7P6YPyZMpmfiWkOHz1S0HNM8PrWAOPIuMN7Uc79uhfdGwitTczct0ysTAeWty4zvFAzHtbPuXEY0Gq6y9E7YWHSedIQ74UNU_FP04qjAFXGD9WiXm6-g8wk_E9GOj5Gyrqk6PQ6b8toO9ujJVxJ556NMZNfHS47J17TKtHjyksDW6TihEaBkFeyqAYdQlqZ-ONHi31MEQ3ydoADRoL7FriUb94hsozYTPoa9Je2Md1HxsL_98RWovDXj8DF4dB4MWdfhaeXa3AWrgofzJrCEmmF_pztC2znvUk3QHYFm88lGLfsGMUWQuHNjK0_qIJtObyhAEUcSoSN4jex5KH8CzrGqIMnGGxLQZqv3Nev-fjuT9cKiZA1q-CTyQwTTDyBYyRE4cSSDDFUpz5jOOALxAuAVU1UjTFGtJicoxDa25-YEJESO-KKRQ-hnSUqh0DbUZNVlZPrKqmTAEpk2Xltsg13CQt_sek3b1ZJaY_IIPjY_iHs3_iQ86ZC

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Patient Laura",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e6831-c64b-7cda-b906-43f05373a901
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Patient Laura Updated",
  "email" : "antoniojaviergr@gmail.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25cc-d9f5-7fdf-bbc2-f872756e6e74
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl
