@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Appointments

GET {{DientesLimpios.API_HostAddress}}/019e6834-cb14-7aa3-be43-d4da8fd4eb41
Accept: application/json
Authorization: Bearer 

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer 

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer 

{
  "PatientId": "01A06B98-A894-7351-8ADF-451B0CFC87FF",
  "DentistId": "01A06B95-C364-70D7-853F-B90436097B7F",
  "OfficeId": "01A06B90-4AFA-748E-BBDF-A376060F83D7",
  "StartDate": "2026-09-23T16:30:00+02:00",
  "EndDate": "2026-09-23T16:45:00+02:00"
}

###


POST {{DientesLimpios.API_HostAddress}}/complete/019E6834-CB14-7AA3-BE43-D4DA8FD4EB41
Accept: application/json
Authorization: Bearer 

###


POST {{DientesLimpios.API_HostAddress}}/cancel/01A0CDCF-71DB-7703-944C-FD2A258B277A
Accept: application/json
Authorization: Bearer 

###


POST {{DientesLimpios.API_HostAddress}}/reminder
Accept: application/json
Authorization: Bearer 
