@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Dentists

GET {{DientesLimpios.API_HostAddress}}/019e25c6-724c-7087-9158-f95d06aa973f
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer CfDJ8FkyPjhqepVDufk2KayVWTeKRhtuEfqKZ5bdm1qZpq3-xu4JSA74GhgEsyStwYdClB-lqSNMilttkfVY6BaCrq7oz26CoG6ubd2qAh7YtyfXnYA1jept5NfhJSVVdndgNy1xbUDNzGpWrUgv2NjOidPgqxVMdpo6YfcI86DuG1EJG-zm5DATNUHFkj5xaIp1ShkGPKOQoXVEoAKcV1t84ha-r8ReYJ1HzCsHDg78z6-vJh-3VJNKy2nor7Vsv5P6QI0uoXJbOccitt6QoXx-mB4BhyQRa6qFjp5T8vEptxiulklPX0XvVGr4d5S8rarMcHpn9AwxsVbf5mdQvImd-k6ir0LW5b_aCzNnuQotTZq1rD6NXKOobQpJcBout1_rcRTYtuLPYbMDS_wHNr5YHuJ2HWn4y8nI1Y3gZ4czafjIqCcJZ-BqivEHG1l-dK6Bkpt01BuuRwr-RS6atBbnRdWHEDjh7HIYZLL9I3JmnyMvG868T43_chWQloJ09Lpd3kVpfz5PHq84_rCOg1FUzuwz7z9jeG-rYHoGOaT_gkKOMtsuVR5YhxgAUSBbCFe0lzYuv-Kl-OTlndi4X_j5TJuusWigbuT16jEFoAGoQ60W-DkcV32o9QKsfZ7DyATkYX3TUo8tf-B4ALag1Sv4wVdeuzAsZgt_PG8wUi-vaodZaOYJhnX_86Lr3DPVwkJABclhMHEmtweT-M5Nbsl96AUtkI5_urbVf_80dllhBydG

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Dentist Daniel",
  "email" : "Daniel@ejemplo.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e682d-dcc4-70db-8af6-198c65039206
Content-Type: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl

{
  "name": "Dentist Daniel Updated",
  "email" : "DanielUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25c6-724c-7087-9158-f95d06aa973f
Accept: application/json
Authorization: Bearer CfDJ8BWtSZFMolhMisRu84y_P9n_WE4yCOFlN0VlV0tFi5P9SnqecQO7Qpomjt6Ja2_SR5SYBpI-jEVPpG9lwBsgytK0K1dl8o5VReqH_NNwSieV2JkbVlOTKk898FvKOjw9atevAPtn4lGqN4-UAUFbC2vZanY5JU8PTjmtMQ6g0XUE2iTkmVmaEwhuoIAe6d64dpWyFPD2f7GVtq9UHdXB7enrZSAk2M3ztQqn6hBAkhSUFioVQvrKcOifWBE-YBzbRtLuNv1DIjs0jVvSFY5bQXgOEu9D4QwHkaptmZnj1wseOyGr9oXUL1yGgSdyN9UaPnIQIw_Rcp6O5KT4dbnIAwUjXvJJUKewLPNAS6deItwrIEM9gwnoEs72l9Ti8fcKUEYkjmsW67n2zM988OThhziretkVIxiW5KHWb8ScNO02UruxBfaGhFVdAKB9hs8ucAHPQYnhTNnkRR_WPHPWYhAJrf63EfqvkQW5fHszCyJFWiMiRyxck4KGjABGDoDbBZwMvREF8Z_aBiOQNB_puyoTPoNWaLz-cWettHK6Q5s8N5w84LezlBthOLFeGl5NNxDdohxm7_AmA1fFTf60I7exeFfEv5DbGxyvlD-pyEy-iRwdos-jaTEO3bcBcpinMgbjZrdwocRn5MAV5y66PcE2xbIWOUwuJC7OKVMo48wK9ywrI06Baf2XhwPAvydCaac69p04pEYS-LNHvoFRfFXgh97LcQxH61VC5T2ahqgl
