@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Offices

GET {{DientesLimpios.API_HostAddress}}/019e25bd-3f14-755c-a08c-1cba409319dd
Accept: application/json
Authorization: Bearer 
###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer 

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Office B"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e682a-fd77-72df-a546-8f99d535beb6
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Office B Updated"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25ba-9326-7a41-8f18-bbf349021ead
Accept: application/json
Authorization: Bearer 
