@DientesLimpios.API_HostAddress = https://localhost:7199/api/v1/Patients

GET {{DientesLimpios.API_HostAddress}}/019e2602-9742-7ef0-b968-e5d40eff6682
Accept: application/json
Authorization: Bearer 

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json
Authorization: Bearer 

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Patient Laura",
  "email" : "antoniojaviergr@gmail.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019e6831-c64b-7cda-b906-43f05373a901
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Patient Laura Updated",
  "email" : "antoniojaviergr@gmail.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019e25cc-d9f5-7fdf-bbc2-f872756e6e74
Accept: application/json
Authorization: Bearer 
