@DientesLimpios.API_HostAddress = https://localhost:7199

POST {{DientesLimpios.API_HostAddress}}/register
Content-Type: application/json

{
  "email": "antonio@ejemplo.com",
  "password": "aA123456!"
}

###


POST {{DientesLimpios.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "antonio@ejemplo.com",
  "password": "aA123456!"
}

